- name: Nextcloud
  hosts: nextcloud-server
  tasks:
    - name: Timezone settings
      become: true
      community.general.timezone:
        name: Europe/Moscow

    - name: Upgrade Software
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes

    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg: 
          - acl
          - apache2
          - libapache2-mod-php
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-pgsql
          - php-zip
          - postgresql-all
          - python3-psycopg2
          - unzip
        state: present
    
    - name: Download and unpack Nextcloud
      become: true
      ansible.builtin.unarchive:
        src: "https://download.nextcloud.com/server/releases/latest.zip"
        dest: "/var/www/html"
        remote_src: yes
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"

    - name: Create Postgresql user
      become: true
      become_user: postgres
      become_method: ansible.builtin.sudo
      community.postgresql.postgresql_user:
        name: dbuser
        password: dbpassword
    
    - name: Create Postgresql database
      become: true
      become_user: postgres
      become_method: ansible.builtin.sudo
      community.postgresql.postgresql_db:
        name: dbnextcloud
        owner: "dbuser"